---
cloudwatch_agent_package_url: >-
  https://amazoncloudwatch-agent.s3.amazonaws.com/debian/amd64/latest/amazon-cloudwatch-agent.deb
cloudwatch_agent_signature_url: >-
  https://amazoncloudwatch-agent.s3.amazonaws.com/debian/amd64/latest/amazon-cloudwatch-agent.deb.sig
cloudwatch_agent_signing_key_url: >-
  https://amazoncloudwatch-agent.s3.amazonaws.com/assets/amazon-cloudwatch-agent.gpg
cloudwatch_agent_expected_fingerprint: "937616F3450B7D806CBD9725D58167303B789C72"
cloudwatch_agent_package_path: /var/tmp/amazon-cloudwatch-agent.deb
cloudwatch_agent_signature_path: /var/tmp/amazon-cloudwatch-agent.deb.sig
cloudwatch_agent_signing_key_path: /var/tmp/amazon-cloudwatch-agent.gpg
cloudwatch_agent_gpg_home: /var/lib/amazon-cloudwatch-agent-verify
cloudwatch_agent_config_path: /opt/aws/amazon-cloudwatch-agent/etc/amazon-cloudwatch-agent.json
cloudwatch_agent_log_group_prefix: "/microcrm/poc"
cloudwatch_agent_metrics_namespace: "MicroCRM/Poc"
cloudwatch_agent_collect_kubernetes_logs: false
cloudwatch_agent_metrics_interval: 60
cloudwatch_agent_log_flush_interval: 5
