workflow:
  rules:
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'
    - if: '$CI_COMMIT_TAG'
    - if: '$CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH'
    - if: '$CI_COMMIT_BRANCH == "dev"'
    - when: never

stages:
  - test
  - quality
  - build
  - release
  - deploy
  - verify

variables:
  FRONTEND_IMAGE: "$CI_REGISTRY_IMAGE/frontend:$CI_COMMIT_SHA"
  BACKEND_IMAGE: "$CI_REGISTRY_IMAGE/backend:$CI_COMMIT_SHA"

include:
  - local: .gitlab/ci/common.yml
  - local: .gitlab/ci/test.yml
  - local: .gitlab/ci/quality.yml
  - local: .gitlab/ci/build.yml
  - local: .gitlab/ci/release.yml
