spring.application.name=microcrm
spring.jpa.hibernate.ddl-auto=validate
spring.liquibase.change-log=classpath:db/changelog/db.changelog-master.yaml
microcrm.deployment.environment=${MICROCRM_DEPLOYMENT_ENVIRONMENT:development}
microcrm.deployment.track=${MICROCRM_DEPLOYMENT_TRACK:stable}
microcrm.release.version=${MICROCRM_RELEASE_VERSION:unreleased}
microcrm.metrics.statsd.host=${MICROCRM_STATSD_HOST:127.0.0.1}
microcrm.metrics.statsd.port=${MICROCRM_STATSD_PORT:8125}
microcrm.monitoring.username=${MICROCRM_MONITORING_USERNAME:monitoring}
microcrm.monitoring.password=${MICROCRM_MONITORING_PASSWORD:}
