apiVersion: v1
kind: Service
metadata:
  name: {{ include "microcrm.fullname" . }}-frontend
  labels:
    {{- include "microcrm.labels" . | nindent 4 }}
    app.kubernetes.io/component: frontend
    microcrm.io/track: stable
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: {{ include "microcrm.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/component: frontend
  ports:
    - name: http
      port: {{ .Values.frontend.service.port }}
      targetPort: http
