{{- if .Values.monitoringAuth.managedSecret.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.monitoringAuth.existingSecret }}
  labels:
    {{- include "microcrm.labels" . | nindent 4 }}
type: Opaque
data:
  {{ .Values.monitoringAuth.usernameKey }}: {{ required "monitoringAuth.managedSecret.username est obligatoire" .Values.monitoringAuth.managedSecret.username | b64enc | quote }}
  {{ .Values.monitoringAuth.passwordKey }}: {{ required "monitoringAuth.managedSecret.passwordBase64 est obligatoire" .Values.monitoringAuth.managedSecret.passwordBase64 | quote }}
{{- end }}
