apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "microcrm.fullname" . }}-backend
  labels:
    {{- include "microcrm.labels" . | nindent 4 }}
spec:
  podSelector:
    matchLabels:
      app.kubernetes.io/name: {{ include "microcrm.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
      app.kubernetes.io/component: backend
  policyTypes: ["Ingress"]
  ingress:
    - from:
        - podSelector:
            matchLabels:
              app.kubernetes.io/name: {{ include "microcrm.name" . }}
              app.kubernetes.io/instance: {{ .Release.Name }}
              app.kubernetes.io/component: frontend
      ports:
        - protocol: TCP
          port: 8080
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "microcrm.fullname" . }}-database
  labels:
    {{- include "microcrm.labels" . | nindent 4 }}
spec:
  podSelector:
    matchLabels:
      app.kubernetes.io/name: {{ include "microcrm.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
      app.kubernetes.io/component: database
  policyTypes: ["Ingress"]
  ingress:
    - from:
        - podSelector:
            matchLabels:
              app.kubernetes.io/name: {{ include "microcrm.name" . }}
              app.kubernetes.io/instance: {{ .Release.Name }}
              app.kubernetes.io/component: backend
        {{- if .Values.canary.enabled }}
        - podSelector:
            matchLabels:
              app.kubernetes.io/name: {{ include "microcrm.name" . }}
              app.kubernetes.io/instance: {{ printf "%s-canary" .Release.Name }}
              app.kubernetes.io/component: backend
              microcrm.io/track: canary
        {{- end }}
      ports:
        - protocol: TCP
          port: 5432
