nameOverride: ""
fullnameOverride: ""

imagePullSecrets: []

registrySecret:
  enabled: false
  name: microcrm-registry
  server: ""
  usernameBase64: ""
  passwordBase64: ""

frontend:
  replicaCount: 1
  image:
    repository: registry.gitlab.com/project_6_group/microcrm/frontend
    tag: replace-me
    digest: ""
    pullPolicy: IfNotPresent
  service:
    port: 80
  resources:
    requests:
      cpu: 50m
      memory: 32Mi
    limits:
      cpu: 250m
      memory: 128Mi

backend:
  replicaCount: 1
  image:
    repository: registry.gitlab.com/project_6_group/microcrm/backend
    tag: replace-me
    digest: ""
    pullPolicy: IfNotPresent
  service:
    port: 8080
  resources:
    requests:
      cpu: 100m
      memory: 256Mi
    limits:
      cpu: 500m
      memory: 512Mi

database:
  image:
    repository: postgres
    tag: 17.10-alpine3.23
    digest: ""
    pullPolicy: IfNotPresent
  name: microcrm
  existingSecret: microcrm-database
  usernameKey: username
  passwordKey: password
  managedSecret:
    enabled: false
    username: microcrm
    passwordBase64: ""
  persistence:
    enabled: true
    size: 2Gi
    storageClass: ""
  resources:
    requests:
      cpu: 100m
      memory: 256Mi
    limits:
      cpu: 500m
      memory: 512Mi

ingress:
  enabled: false
  className: ""
  host: microcrm.local
  annotations: {}
  tls: []
