frontend:
  image:
    repository: microcrm-frontend
    tag: local
    pullPolicy: Never

backend:
  image:
    repository: microcrm-backend
    tag: local
    pullPolicy: Never

database:
  persistence:
    size: 1Gi

ingress:
  enabled: true
  className: nginx
  host: microcrm.local
