{{- if .Values.database.managedSecret.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.database.existingSecret }}
  labels:
    {{- include "microcrm.labels" . | nindent 4 }}
type: Opaque
data:
  {{ .Values.database.usernameKey }}: {{ .Values.database.managedSecret.username | b64enc | quote }}
  {{ .Values.database.passwordKey }}: {{ required "database.managedSecret.passwordBase64 est obligatoire lorsque database.managedSecret.enabled=true" .Values.database.managedSecret.passwordBase64 | quote }}
{{- end }}
