apiVersion: v1
kind: Service
metadata:
  name: {{ include "microcrm.fullname" . }}-database
  labels:
    {{- include "microcrm.labels" . | nindent 4 }}
    app.kubernetes.io/component: database
spec:
  clusterIP: None
  selector:
    app.kubernetes.io/name: {{ include "microcrm.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/component: database
  ports:
    - name: postgresql
      port: 5432
      targetPort: postgresql
